{% set name = "xorg-libXrender" %}
{% set version = "0.9.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/lib/{{ name.split('-')[1] }}-{{ version }}.tar.xz
  sha256: b832128da48b39c8d608224481743403ad1691bf4e554e4be9c174df171d1b97

build:
  number: 1
  # xorg-libxdmcp, libxcb, libx11, libice aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - gnuconfig
    - make
    - autoconf
    - automake
    - gettext
    - libtool
  host:
    - xorg-libx11 {{ xorg_libx11 }}
    - xorg-xorgproto {{ xorg_xorgproto }}
    - xorg-util-macros ==1.20.2

test:
  commands:
    - test -f $PREFIX/lib/libXrender.dylib  # [osx]
    - test -f $PREFIX/lib/libXrender.so     # [linux]

about:
  home: https://www.x.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxrender
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libxrender
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org X11 direct rendering library.
  description: |
    The X.org X11 direct rendering library.

extra:
  recipe-maintainers:
    - pkgw
